apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- deployment-increase-replicas.yaml

images:
- name: ykhadilkar/spring-boot-api
  newName: ykhadilkar/spring-boot-api
  newTag: qa
