---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
inputs:
  - name: spring-boot-service
outputs:
  - name: spring-boot-service-out
params:
  CONTEXT: spring-boot-service
run:
  path: build
