# name: Java CI with CF Push

# on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 11
#       uses: actions/setup-java@v1
#       with:
#         java-version: 11
#     - name: Build with Maven
#       run: mvn -B package --file pom.xml
#     - name: Upload JAR
#       uses: actions/upload-artifact@v1
#       with:
#         name: spring-boot-api
#         path: target/spring-boot-api-0.0.1-SNAPSHOT.jar


#   deploy:
#     runs-on: ubuntu-18.04
#     needs: build

#     steps:
#       - name: Download JAR
#         uses: actions/download-artifact@v1
#         with:
#           name: spring-boot-api
#       - uses: d3sandoval/cloud-foundry-action@1.1.1
#         with:
#           args: push spring-boot-api -p spring-boot-api/spring-boot-api-0.0.1-SNAPSHOT.jar  --random-route
#         env:
#           CF_API: https://donotuseapi.run.pivotal.io
#           CF_USERNAME: ${{ secrets.CF_USER }}
#           CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
#           CF_TARGET_ORG: cf-demo-org
#           CF_TARGET_SPACE: test
